language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sbkl/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true sbkl/frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-938090705732"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
